### ISSUE TITLE
partial camp PRs that need some love for release

### ISSUE THREAD

**Issue by trws** [LLNL/RAJA#1096]
As discussed on Monday, we need to move some camp PRs through to get ready for the upcoming raja release.  Some are basically ready to go and just waiting on a button push or the CI to come back, I'm running through those now.  The ones listed here need some more work before I can merge them, and seem to be something we need.  I'll keep this up to date as a tracking issue for this release:

* [x] LLNL/camp#66: @artv3, currently does not build because the get_event_erased method hasn't been plumbed through the type-erased resource
* [x] LLNL/camp#63: sycl resources, I rebased and formatted this one myself, waiting on a thumbs-up from the author to merge
* [x] LLNL/camp#54: fix EventProxy conversions, this one seems to be ready but stalled out waiting for app-team feedback @MrBurmark, @rhornung67, a look here would be very helpful
* [x] LLNL/camp#53: this one adds a wait method on the type erased resource, should be good to go but needed a rebase which I gave it, if the tests pass this one can go in right away
* [x] LLNL/camp#45: hip allocator, @artv3 / @davidbeckingsale is this issue still relevant? If so it needs a rebase so it can be pulled in, and we'll want to create an issue to track reverting this when rocm is fixed.
* [x] LLNL/camp#73: change allocation behavior for resources

**Comment by rhornung67** [comment]
Thanks for the status report @trws

**Comment by artv3** [comment]
I think we just addressed https://github.com/LLNL/camp/pull/66 . This will enable us to merge https://github.com/LLNL/RAJA/pull/1029

**Comment by trws** [comment]
All of the PRs listed here originally are done and merged.  I would be alright with cutting a release, but remembered that we discussed changing the allocation behavior so that's been added to the list.  @rhornung67, let me know if you'd prefer to make that part of a later release and I can cut a camp release right away.

**Comment by rhornung67** [comment]
If you have time and can get the allocation change done by the end of this week, I think we should do it and tag a camp release after that. I want to get the perf suite release out with the new raja release and we are roadblocked on rocm 4.3 and this camp change may fix the issue.  Let me know what you decide to do.
