### ISSUE TITLE
TODO: Lauch support

### ISSUE THREAD

**Issue by artv3** [LLNL/RAJA#1383]
This issue pulls in various reported issues to create a list of tasks. 

- [ ] CHAI/Plugin support (https://github.com/LLNL/RAJA/issues/1379, https://github.com/LLNL/RAJA/issues/1333) : in progress https://github.com/LLNL/RAJA/pull/1381
- [ ] Add Sycl unit test
- [ ] Add dynamic shared memory unit test
- [ ] Develop interface for perfectly nested loops, allows support for omp collapse, application requested patterns (https://github.com/LLNL/RAJA/issues/1314, https://github.com/LLNL/RAJA/issues/1346). 
- [ ] add detailed examples in ReadtheDocs
